require "spec"
ENV["SHOMEN_SECRET"] = "spec-secret"
require "../src/shomen"
require "./support/process"
require "./support/client"
require "./support/routes"
require "./support/events"
require "./support/store"
require "./support/projections"
